language: node_js
node_js:
  - 12
cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    - node_modules
    # we also need to cache folder with Cypress binary
    - ~/.cache
install: yarn install
script:
  - yarn build
  - yarn test
  - yarn e2e-ci # create aws-exports file and run cypress
