language: node_js
node_js:
  - 12
cache:
  directories:
    # - node_modules
    - ~/.cache
script:
  - npm install codecov -g
  - yarn build
  - yarn test
  - yarn build-storybook
  - yarn e2e
after_success:
  - codecov
